import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "pt-BR" | "en" | "es" | "fr";

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    app_name: "OrderControl",
    home: "Início",
    menu: "Cardápio",
    cart: "Carrinho",
    orders: "Pedidos",
    profile: "Perfil",
    admin: "Admin",
    dashboard: "Painel",
    settings: "Configurações",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    search: "Buscar",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    back: "Voltar",
    logout: "Sair",
    login: "Entrar",
    register: "Cadastrar",
    email: "E-mail",
    password: "Senha",
    name: "Nome completo",
    phone: "Telefone",
    address: "Endereço",
    city: "Cidade",
    zip_code: "CEP",
    admin_login: "Acesso Administrativo",
    customer_login: "Acesso do Cliente",
    dont_have_account: "Não tem conta?",
    already_have_account: "Já tem conta?",
    forgot_password: "Esqueceu a senha?",
    welcome: "Bem-vindo,",
    featured: "Destaques",
    categories: "Categorias",
    see_menu: "Ver Cardápio",
    contact_whatsapp: "Falar no WhatsApp",
    open_now: "Aberto agora",
    closed: "Fechado",
    opening_hours: "Horário de funcionamento",
    add_to_cart: "Adicionar ao carrinho",
    description: "Descrição",
    price: "Preço",
    extras: "Adicionais",
    quantity: "Quantidade",
    empty_cart: "Carrinho vazio",
    empty_cart_desc: "Adicione itens do cardápio para começar seu pedido",
    subtotal: "Subtotal",
    delivery_fee: "Taxa de entrega",
    total: "Total",
    checkout: "Finalizar Pedido",
    remove: "Remover",
    delivery: "Entrega",
    pickup: "Retirada",
    payment_method: "Forma de pagamento",
    pix: "PIX",
    cash: "Dinheiro",
    credit_card: "Cartão de Crédito",
    pay_on_delivery: "Pagar na Entrega",
    neighborhood: "Bairro",
    reference: "Ponto de referência",
    place_order: "Fazer Pedido",
    order_confirmed: "Pedido confirmado!",
    order_number: "Número do pedido",
    estimated_time: "Tempo estimado",
    minutes: "minutos",
    order_received: "Pedido recebido",
    preparing: "Preparando",
    ready: "Pronto",
    out_for_delivery: "Saiu para entrega",
    delivered: "Entregue",
    cancelled: "Cancelado",
    track_order: "Acompanhar pedido",
    order_history: "Histórico de pedidos",
    orders_today: "Pedidos hoje",
    revenue_today: "Receita hoje",
    active_orders: "Pedidos ativos",
    monthly_revenue: "Receita mensal",
    most_sold: "Mais vendidos",
    new_order: "Novo pedido",
    accept: "Aceitar",
    reject: "Rejeitar",
    product_name: "Nome do produto",
    category: "Categoria",
    image: "Imagem",
    available: "Disponível",
    unavailable: "Indisponível",
    add_product: "Adicionar produto",
    edit_product: "Editar produto",
    promotions: "Promoções",
    discount: "Desconto",
    original_price: "Preço original",
    promo_price: "Preço promocional",
    active: "Ativo",
    inactive: "Inativo",
    restaurant_name: "Nome do restaurante",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Redes Sociais",
    delivery_areas: "Áreas de Entrega",
    min_order: "Pedido mínimo",
    daily_report: "Relatório Diário",
    monthly_report: "Relatório Mensal",
    export_pdf: "Exportar PDF",
    my_orders: "Meus Pedidos",
    saved_addresses: "Endereços salvos",
    edit_profile: "Editar perfil",
    language: "Idioma",
  },
  "en": {
    app_name: "OrderControl",
    home: "Home",
    menu: "Menu",
    cart: "Cart",
    orders: "Orders",
    profile: "Profile",
    admin: "Admin",
    dashboard: "Dashboard",
    settings: "Settings",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    back: "Back",
    logout: "Logout",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Full name",
    phone: "Phone",
    address: "Address",
    city: "City",
    zip_code: "Zip Code",
    admin_login: "Admin Access",
    customer_login: "Customer Access",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    forgot_password: "Forgot password?",
    welcome: "Welcome,",
    featured: "Featured",
    categories: "Categories",
    see_menu: "See Menu",
    contact_whatsapp: "Contact via WhatsApp",
    open_now: "Open now",
    closed: "Closed",
    opening_hours: "Opening hours",
    add_to_cart: "Add to cart",
    description: "Description",
    price: "Price",
    extras: "Extras",
    quantity: "Quantity",
    empty_cart: "Empty cart",
    empty_cart_desc: "Add items from the menu to start your order",
    subtotal: "Subtotal",
    delivery_fee: "Delivery fee",
    total: "Total",
    checkout: "Checkout",
    remove: "Remove",
    delivery: "Delivery",
    pickup: "Pickup",
    payment_method: "Payment method",
    pix: "PIX",
    cash: "Cash",
    credit_card: "Credit Card",
    pay_on_delivery: "Pay on Delivery",
    neighborhood: "Neighborhood",
    reference: "Reference point",
    place_order: "Place Order",
    order_confirmed: "Order confirmed!",
    order_number: "Order number",
    estimated_time: "Estimated time",
    minutes: "minutes",
    order_received: "Order received",
    preparing: "Preparing",
    ready: "Ready",
    out_for_delivery: "Out for delivery",
    delivered: "Delivered",
    cancelled: "Cancelled",
    track_order: "Track order",
    order_history: "Order history",
    orders_today: "Orders today",
    revenue_today: "Revenue today",
    active_orders: "Active orders",
    monthly_revenue: "Monthly revenue",
    most_sold: "Most sold",
    new_order: "New order",
    accept: "Accept",
    reject: "Reject",
    product_name: "Product name",
    category: "Category",
    image: "Image",
    available: "Available",
    unavailable: "Unavailable",
    add_product: "Add product",
    edit_product: "Edit product",
    promotions: "Promotions",
    discount: "Discount",
    original_price: "Original price",
    promo_price: "Promo price",
    active: "Active",
    inactive: "Inactive",
    restaurant_name: "Restaurant name",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Social Media",
    delivery_areas: "Delivery Areas",
    min_order: "Minimum order",
    daily_report: "Daily Report",
    monthly_report: "Monthly Report",
    export_pdf: "Export PDF",
    my_orders: "My Orders",
    saved_addresses: "Saved addresses",
    edit_profile: "Edit profile",
    language: "Language",
  },
  "es": {
    app_name: "OrderControl",
    home: "Inicio",
    menu: "Menú",
    cart: "Carrito",
    orders: "Pedidos",
    profile: "Perfil",
    admin: "Admin",
    dashboard: "Panel",
    settings: "Configuración",
    save: "Guardar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Agregar",
    search: "Buscar",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    back: "Volver",
    logout: "Salir",
    login: "Entrar",
    register: "Registrarse",
    email: "Correo",
    password: "Contraseña",
    name: "Nombre completo",
    phone: "Teléfono",
    address: "Dirección",
    city: "Ciudad",
    zip_code: "Código postal",
    admin_login: "Acceso Admin",
    customer_login: "Acceso Cliente",
    dont_have_account: "¿No tienes cuenta?",
    already_have_account: "¿Ya tienes cuenta?",
    forgot_password: "¿Olvidaste tu contraseña?",
    welcome: "¡Bienvenido,",
    featured: "Destacados",
    categories: "Categorías",
    see_menu: "Ver Menú",
    contact_whatsapp: "Contactar por WhatsApp",
    open_now: "Abierto ahora",
    closed: "Cerrado",
    opening_hours: "Horario de atención",
    add_to_cart: "Agregar al carrito",
    description: "Descripción",
    price: "Precio",
    extras: "Extras",
    quantity: "Cantidad",
    empty_cart: "Carrito vacío",
    empty_cart_desc: "Agrega artículos del menú para comenzar tu pedido",
    subtotal: "Subtotal",
    delivery_fee: "Costo de entrega",
    total: "Total",
    checkout: "Finalizar Pedido",
    remove: "Eliminar",
    delivery: "Entrega",
    pickup: "Recoger",
    payment_method: "Método de pago",
    pix: "PIX",
    cash: "Efectivo",
    credit_card: "Tarjeta de crédito",
    pay_on_delivery: "Pagar al recibir",
    neighborhood: "Barrio",
    reference: "Punto de referencia",
    place_order: "Hacer Pedido",
    order_confirmed: "¡Pedido confirmado!",
    order_number: "Número de pedido",
    estimated_time: "Tiempo estimado",
    minutes: "minutos",
    order_received: "Pedido recibido",
    preparing: "Preparando",
    ready: "Listo",
    out_for_delivery: "En camino",
    delivered: "Entregado",
    cancelled: "Cancelado",
    track_order: "Seguir pedido",
    order_history: "Historial de pedidos",
    orders_today: "Pedidos hoy",
    revenue_today: "Ingresos hoy",
    active_orders: "Pedidos activos",
    monthly_revenue: "Ingresos mensuales",
    most_sold: "Más vendidos",
    new_order: "Nuevo pedido",
    accept: "Aceptar",
    reject: "Rechazar",
    product_name: "Nombre del producto",
    category: "Categoría",
    image: "Imagen",
    available: "Disponible",
    unavailable: "No disponible",
    add_product: "Agregar producto",
    edit_product: "Editar producto",
    promotions: "Promociones",
    discount: "Descuento",
    original_price: "Precio original",
    promo_price: "Precio promocional",
    active: "Activo",
    inactive: "Inactivo",
    restaurant_name: "Nombre del restaurante",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Redes Sociales",
    delivery_areas: "Áreas de entrega",
    min_order: "Pedido mínimo",
    daily_report: "Informe diario",
    monthly_report: "Informe mensual",
    export_pdf: "Exportar PDF",
    my_orders: "Mis Pedidos",
    saved_addresses: "Direcciones guardadas",
    edit_profile: "Editar perfil",
    language: "Idioma",
  },
  "fr": {
    app_name: "OrderControl",
    home: "Accueil",
    menu: "Menu",
    cart: "Panier",
    orders: "Commandes",
    profile: "Profil",
    admin: "Admin",
    dashboard: "Tableau de bord",
    settings: "Paramètres",
    save: "Enregistrer",
    cancel: "Annuler",
    confirm: "Confirmer",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    search: "Rechercher",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    back: "Retour",
    logout: "Déconnexion",
    login: "Connexion",
    register: "S'inscrire",
    email: "Email",
    password: "Mot de passe",
    name: "Nom complet",
    phone: "Téléphone",
    address: "Adresse",
    city: "Ville",
    zip_code: "Code postal",
    admin_login: "Accès Admin",
    customer_login: "Accès Client",
    dont_have_account: "Pas de compte?",
    already_have_account: "Déjà un compte?",
    forgot_password: "Mot de passe oublié?",
    welcome: "Bienvenue,",
    featured: "À la une",
    categories: "Catégories",
    see_menu: "Voir le Menu",
    contact_whatsapp: "Contacter via WhatsApp",
    open_now: "Ouvert maintenant",
    closed: "Fermé",
    opening_hours: "Heures d'ouverture",
    add_to_cart: "Ajouter au panier",
    description: "Description",
    price: "Prix",
    extras: "Suppléments",
    quantity: "Quantité",
    empty_cart: "Panier vide",
    empty_cart_desc: "Ajoutez des articles du menu pour commencer votre commande",
    subtotal: "Sous-total",
    delivery_fee: "Frais de livraison",
    total: "Total",
    checkout: "Finaliser la Commande",
    remove: "Supprimer",
    delivery: "Livraison",
    pickup: "À emporter",
    payment_method: "Mode de paiement",
    pix: "PIX",
    cash: "Espèces",
    credit_card: "Carte de crédit",
    pay_on_delivery: "Payer à la livraison",
    neighborhood: "Quartier",
    reference: "Point de référence",
    place_order: "Passer la Commande",
    order_confirmed: "Commande confirmée!",
    order_number: "Numéro de commande",
    estimated_time: "Délai estimé",
    minutes: "minutes",
    order_received: "Commande reçue",
    preparing: "En préparation",
    ready: "Prête",
    out_for_delivery: "En livraison",
    delivered: "Livrée",
    cancelled: "Annulée",
    track_order: "Suivre la commande",
    order_history: "Historique des commandes",
    orders_today: "Commandes aujourd'hui",
    revenue_today: "Revenus aujourd'hui",
    active_orders: "Commandes actives",
    monthly_revenue: "Revenus mensuels",
    most_sold: "Les plus vendus",
    new_order: "Nouvelle commande",
    accept: "Accepter",
    reject: "Refuser",
    product_name: "Nom du produit",
    category: "Catégorie",
    image: "Image",
    available: "Disponible",
    unavailable: "Indisponible",
    add_product: "Ajouter un produit",
    edit_product: "Modifier le produit",
    promotions: "Promotions",
    discount: "Réduction",
    original_price: "Prix original",
    promo_price: "Prix promotionnel",
    active: "Actif",
    inactive: "Inactif",
    restaurant_name: "Nom du restaurant",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Réseaux Sociaux",
    delivery_areas: "Zones de livraison",
    min_order: "Commande minimum",
    daily_report: "Rapport journalier",
    monthly_report: "Rapport mensuel",
    export_pdf: "Exporter PDF",
    my_orders: "Mes Commandes",
    saved_addresses: "Adresses enregistrées",
    edit_profile: "Modifier le profil",
    language: "Langue",
  },
};

const LangContext = createContext<{
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
} | null>(null);

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("pt-BR");

  useEffect(() => {
    AsyncStorage.getItem("@ordercontrol_lang").then((l) => {
      if (l) setLanguageState(l as Language);
    });
  }, []);

  function setLanguage(l: Language) {
    setLanguageState(l);
    AsyncStorage.setItem("@ordercontrol_lang", l);
  }

  function t(key: string): string {
    return translations[language][key] ?? translations["pt-BR"][key] ?? key;
  }

  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
