import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "pt-BR" | "pt-PT" | "en" | "es" | "fr";

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    app_name: "OrderControl",
    home: "Início",
    menu: "Cardápio",
    cart: "Carrinho",
    orders: "Pedidos",
    profile: "Perfil",
    admin: "Admin",
    dashboard: "Painel",
    settings: "Configurações",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    search: "Buscar",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    back: "Voltar",
    logout: "Sair",
    login: "Entrar",
    register: "Cadastrar",
    email: "E-mail",
    password: "Senha",
    name: "Nome completo",
    phone: "Telefone",
    address: "Endereço",
    city: "Cidade",
    zip_code: "CEP",
    admin_login: "Acesso Administrativo",
    customer_login: "Acesso do Cliente",
    dont_have_account: "Não tem conta?",
    already_have_account: "Já tem conta?",
    forgot_password: "Esqueceu a senha?",
    welcome: "Bem-vindo,",
    featured: "Destaques",
    categories: "Categorias",
    see_menu: "Ver Cardápio",
    contact_whatsapp: "Falar no WhatsApp",
    open_now: "Aberto agora",
    closed: "Fechado",
    opening_hours: "Horário de funcionamento",
    add_to_cart: "Adicionar ao carrinho",
    description: "Descrição",
    price: "Preço",
    extras: "Adicionais",
    quantity: "Quantidade",
    empty_cart: "Carrinho vazio",
    empty_cart_desc: "Adicione itens do cardápio para começar seu pedido",
    subtotal: "Subtotal",
    delivery_fee: "Taxa de entrega",
    total: "Total",
    checkout: "Finalizar Pedido",
    remove: "Remover",
    delivery: "Entrega",
    pickup: "Retirada",
    payment_method: "Forma de pagamento",
    pix: "PIX",
    cash: "Dinheiro",
    credit_card: "Cartão de Crédito",
    pay_on_delivery: "Pagar na Entrega",
    neighborhood: "Bairro",
    reference: "Ponto de referência",
    place_order: "Fazer Pedido",
    order_confirmed: "Pedido confirmado!",
    order_number: "Número do pedido",
    estimated_time: "Tempo estimado",
    minutes: "minutos",
    order_received: "Pedido recebido",
    preparing: "Preparando",
    ready: "Pronto",
    out_for_delivery: "Saiu para entrega",
    delivered: "Entregue",
    cancelled: "Cancelado",
    track_order: "Acompanhar pedido",
    order_history: "Histórico de pedidos",
    orders_today: "Pedidos hoje",
    revenue_today: "Receita hoje",
    active_orders: "Pedidos ativos",
    monthly_revenue: "Receita mensal",
    most_sold: "Mais vendidos",
    new_order: "Novo pedido",
    accept: "Aceitar",
    reject: "Rejeitar",
    product_name: "Nome do produto",
    category: "Categoria",
    image: "Imagem",
    available: "Disponível",
    unavailable: "Indisponível",
    add_product: "Adicionar produto",
    edit_product: "Editar produto",
    promotions: "Promoções",
    discount: "Desconto",
    original_price: "Preço original",
    promo_price: "Preço promocional",
    active: "Ativo",
    inactive: "Inativo",
    restaurant_name: "Nome do restaurante",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Redes Sociais",
    delivery_areas: "Áreas de Entrega",
    min_order: "Pedido mínimo",
    daily_report: "Relatório Diário",
    monthly_report: "Relatório Mensal",
    export_pdf: "Exportar PDF",
    my_orders: "Meus Pedidos",
    saved_addresses: "Endereços salvos",
    edit_profile: "Editar perfil",
    language: "Idioma",
    chat: "Chat",
    chat_support: "Chat com Suporte",
    customer_chats: "Conversas dos Clientes",
    messages: "Mensagens",
    send: "Enviar",
    write_message: "Escreva uma mensagem...",
    no_messages: "Nenhuma mensagem ainda",
    start_conversation: "Inicie uma conversa com o restaurante!",
    login_to_chat: "Faça login para acessar o suporte",
    restaurant_online: "Online • Geralmente responde rápido",
    restaurant_info: "Informações do Restaurante",
    cover_photo: "Foto de Capa",
    logo_photo: "Logo do Restaurante",
    logo_photo_desc: "Toque para alterar o logo",
    change_photo: "Alterar foto",
    save_changes: "Salvar Alterações",
    saving: "Salvando...",
    changes_saved: "Configurações salvas com sucesso!",
    tagline: "Slogan do restaurante",
    phone_label: "Telefone",
    social_links: "Redes Sociais",
    manage_orders: "Gerenciar Pedidos",
    management: "Gerenciamento",
    active_orders_section: "Pedidos Ativos",
    see_all: "Ver todos",
    ready_btn: "Pronto",
    send_btn: "Enviar",
    delivered_btn: "Entregue",
    admin_panel: "Painel Admin",
    hello: "Olá,",
    view_store: "Ver Loja",
    login_to_manage: "Faça login para gerenciar seu perfil",
    register_link: "Cadastre-se",
    admin_badge: "ADMINISTRADOR",
    access_admin: "Acessar Painel Admin",
    no_orders_yet: "Nenhum pedido ainda",
    no_orders_desc: "Seus pedidos aparecerão aqui",
    order_items: "Itens do Pedido",
    order_summary: "Resumo do Pedido",
    delivery_type: "Tipo de Entrega",
    delivery_address_section: "Endereço de Entrega",
    prefer_whatsapp: "Prefere pedir pelo WhatsApp?",
    order_via_whatsapp: "Pedir pelo WhatsApp",
    processing: "Processando...",
    confirm_order: "Confirmar Pedido",
    info: "Informação",
    all: "Todos",
    no_products_found: "Nenhum produto encontrado",
    try_other_category: "Tente outra categoria ou busca",
    free: "Grátis",
    pix: "PIX",
    login_to_view_orders: "Faça login para ver seus pedidos",
    make_first_order: "Faça seu primeiro pedido!",
    order_not_found: "Pedido não encontrado",
    product_not_found: "Produto não encontrado",
    order_problem: "Problemas com seu pedido?",
    login_required: "Faça login para continuar",
    provide_delivery_address: "Informe o endereço de entrega",
    summary: "Resumo",
    item_singular: "item",
    items_plural: "itens",
    status_received: "Pedido recebido",
    status_preparing: "Preparando",
    status_ready: "Pronto para entrega",
    status_delivering: "Saiu para entrega",
    status_delivered: "Entregue",
    status_cancelled: "Cancelado",
    whatsapp_default_msg: "Olá! Gostaria de fazer um pedido.",
    whatsapp_order_inquiry: "Olá! Tenho uma dúvida sobre o pedido",
    total_orders: "Total de pedidos",
    total_revenue: "Receita total",
    avg_order: "Ticket médio",
    today: "Hoje",
    week: "Semana",
    month_label: "Mês",
    best_sellers: "Produtos mais vendidos",
    recent_orders_section: "Pedidos recentes",
    no_data: "Nenhum dado disponível",
    no_orders_period: "Sem pedidos neste período",
    savings: "Economia",
    advance_to: "Avançar para:",
    no_orders_found: "Nenhum pedido encontrado",
    reports_title: "Relatórios",
    all_filter: "Todos",
    received_plural: "Recebidos",
    ready_plural: "Prontos",
    delivered_plural: "Entregues",
    cancelled_plural: "Cancelados",
    delivering_filter: "Entrega",
    remove: "Remover",
    export_btn: "Exportar",
    products: "Produtos",
    n_products: "{n} produtos",
    register_customer: "Cadastrar como cliente",
    register_customer_title: "Criar conta de cliente",
    create_restaurant: "Criar Restaurante",
    create_restaurant_subtitle: "Registre seu restaurante e comece a receber pedidos",
    create_restaurant_btn: "Criar meu restaurante",
    enter_restaurant_code: "Código do restaurante",
    restaurant_code_hint: "Peça o código de 6 dígitos ao dono do restaurante",
    your_restaurant_code: "Código do seu restaurante",
    share_code_hint: "Compartilhe este código com seus clientes para que se cadastrem no app",
    copy: "Copiar",
    copied: "Copiado!",
    restaurant_created: "Restaurante criado com sucesso!",
    code_save_hint: "Guarde este código. Ele também fica disponível em Admin → Configurações.",
    change_password: "Alterar Senha",
    current_password: "Senha atual",
    new_password: "Nova senha",
    confirm_password: "Confirmar senha",
    confirm_new_password: "Confirmar nova senha",
    passwords_dont_match: "As senhas não conferem",
    password_changed: "Senha alterada com sucesso!",
    admin_your_name: "Seu nome (administrador)",
    terms_of_service: "Termos de Uso",
    privacy_policy: "Política de Privacidade",
    fill_password_fields: "Preencha todos os campos de senha",
    error_change_password: "Erro ao alterar senha",
    fill_email_password: "Preencha e-mail e senha",
    invalid_credentials: "E-mail ou senha incorretos. Verifique e tente novamente.",
    welcome_back: "Bem-vindo de volta!",
    or: "ou",
    fill_required_fields: "Preencha nome, e-mail, senha e código do restaurante",
    fill_all_required: "Preencha todos os campos obrigatórios",
    password_min_length: "Senha deve ter pelo menos 6 caracteres",
    error_register: "Erro ao cadastrar",
    error_create_restaurant: "Erro ao criar restaurante",
    fill_form_below: "Preencha os dados abaixo",
    error_pdf: "Erro ao gerar o relatório PDF.",
    notifications: "Notificações",
    no_notifications: "Nenhuma notificação",
    notifications_appear_here: "Atualizações dos seus pedidos aparecerão aqui",
  },
  "en": {
    app_name: "OrderControl",
    home: "Home",
    menu: "Menu",
    cart: "Cart",
    orders: "Orders",
    profile: "Profile",
    admin: "Admin",
    dashboard: "Dashboard",
    settings: "Settings",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    back: "Back",
    logout: "Logout",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Full name",
    phone: "Phone",
    address: "Address",
    city: "City",
    zip_code: "Zip Code",
    admin_login: "Admin Access",
    customer_login: "Customer Access",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    forgot_password: "Forgot password?",
    welcome: "Welcome,",
    featured: "Featured",
    categories: "Categories",
    see_menu: "See Menu",
    contact_whatsapp: "Contact via WhatsApp",
    open_now: "Open now",
    closed: "Closed",
    opening_hours: "Opening hours",
    add_to_cart: "Add to cart",
    description: "Description",
    price: "Price",
    extras: "Extras",
    quantity: "Quantity",
    empty_cart: "Empty cart",
    empty_cart_desc: "Add items from the menu to start your order",
    subtotal: "Subtotal",
    delivery_fee: "Delivery fee",
    total: "Total",
    checkout: "Checkout",
    remove: "Remove",
    delivery: "Delivery",
    pickup: "Pickup",
    payment_method: "Payment method",
    pix: "PIX",
    cash: "Cash",
    credit_card: "Credit Card",
    pay_on_delivery: "Pay on Delivery",
    neighborhood: "Neighborhood",
    reference: "Reference point",
    place_order: "Place Order",
    order_confirmed: "Order confirmed!",
    order_number: "Order number",
    estimated_time: "Estimated time",
    minutes: "minutes",
    order_received: "Order received",
    preparing: "Preparing",
    ready: "Ready",
    out_for_delivery: "Out for delivery",
    delivered: "Delivered",
    cancelled: "Cancelled",
    track_order: "Track order",
    order_history: "Order history",
    orders_today: "Orders today",
    revenue_today: "Revenue today",
    active_orders: "Active orders",
    monthly_revenue: "Monthly revenue",
    most_sold: "Most sold",
    new_order: "New order",
    accept: "Accept",
    reject: "Reject",
    product_name: "Product name",
    category: "Category",
    image: "Image",
    available: "Available",
    unavailable: "Unavailable",
    add_product: "Add product",
    edit_product: "Edit product",
    promotions: "Promotions",
    discount: "Discount",
    original_price: "Original price",
    promo_price: "Promo price",
    active: "Active",
    inactive: "Inactive",
    restaurant_name: "Restaurant name",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Social Media",
    delivery_areas: "Delivery Areas",
    min_order: "Minimum order",
    daily_report: "Daily Report",
    monthly_report: "Monthly Report",
    export_pdf: "Export PDF",
    my_orders: "My Orders",
    saved_addresses: "Saved addresses",
    edit_profile: "Edit profile",
    language: "Language",
    chat: "Chat",
    chat_support: "Support Chat",
    customer_chats: "Customer Conversations",
    messages: "Messages",
    send: "Send",
    write_message: "Write a message...",
    no_messages: "No messages yet",
    start_conversation: "Start a conversation with the restaurant!",
    login_to_chat: "Login to access support",
    restaurant_online: "Online • Usually replies quickly",
    restaurant_info: "Restaurant Information",
    cover_photo: "Cover Photo",
    logo_photo: "Restaurant Logo",
    logo_photo_desc: "Tap to change the logo",
    change_photo: "Change photo",
    save_changes: "Save Changes",
    saving: "Saving...",
    changes_saved: "Settings saved successfully!",
    tagline: "Restaurant slogan",
    phone_label: "Phone",
    social_links: "Social Media",
    manage_orders: "Manage Orders",
    management: "Management",
    active_orders_section: "Active Orders",
    see_all: "See all",
    ready_btn: "Ready",
    send_btn: "Send",
    delivered_btn: "Delivered",
    admin_panel: "Admin Panel",
    hello: "Hello,",
    view_store: "View Store",
    login_to_manage: "Login to manage your profile",
    register_link: "Sign up",
    admin_badge: "ADMINISTRATOR",
    access_admin: "Access Admin Panel",
    no_orders_yet: "No orders yet",
    no_orders_desc: "Your orders will appear here",
    order_items: "Order Items",
    order_summary: "Order Summary",
    delivery_type: "Delivery Type",
    delivery_address_section: "Delivery Address",
    prefer_whatsapp: "Prefer to order via WhatsApp?",
    order_via_whatsapp: "Order via WhatsApp",
    processing: "Processing...",
    confirm_order: "Confirm Order",
    info: "Information",
    free: "Free",
    pix: "PIX",
    login_to_view_orders: "Sign in to view your orders",
    no_orders_yet: "No orders yet",
    make_first_order: "Place your first order!",
    order_not_found: "Order not found",
    product_not_found: "Product not found",
    order_problem: "Issues with your order?",
    login_required: "Sign in to continue",
    provide_delivery_address: "Please enter your delivery address",
    summary: "Summary",
    item_singular: "item",
    items_plural: "items",
    status_received: "Order received",
    status_preparing: "Preparing",
    status_ready: "Ready for pickup",
    status_delivering: "Out for delivery",
    status_delivered: "Delivered",
    status_cancelled: "Cancelled",
    whatsapp_default_msg: "Hello! I'd like to place an order.",
    whatsapp_order_inquiry: "Hello! I have a question about order",
    total_orders: "Total orders",
    total_revenue: "Total revenue",
    avg_order: "Avg. order",
    today: "Today",
    week: "Week",
    month_label: "Month",
    best_sellers: "Best sellers",
    recent_orders_section: "Recent orders",
    no_data: "No data available",
    no_orders_period: "No orders in this period",
    savings: "Savings",
    advance_to: "Advance to:",
    no_orders_found: "No orders found",
    reports_title: "Reports",
    all_filter: "All",
    received_plural: "Received",
    ready_plural: "Ready",
    delivered_plural: "Delivered",
    cancelled_plural: "Cancelled",
    delivering_filter: "Delivery",
    remove: "Remove",
    export_btn: "Export",
    products: "Products",
    n_products: "{n} products",
    register_customer: "Register as customer",
    register_customer_title: "Create customer account",
    create_restaurant: "Create Restaurant",
    create_restaurant_subtitle: "Register your restaurant and start receiving orders",
    create_restaurant_btn: "Create my restaurant",
    enter_restaurant_code: "Restaurant code",
    restaurant_code_hint: "Ask the restaurant owner for the 6-digit code",
    your_restaurant_code: "Your restaurant code",
    share_code_hint: "Share this code with your customers so they can register on the app",
    copy: "Copy",
    copied: "Copied!",
    restaurant_created: "Restaurant created successfully!",
    code_save_hint: "Save this code. It's also available in Admin → Settings.",
    change_password: "Change Password",
    current_password: "Current password",
    new_password: "New password",
    confirm_password: "Confirm password",
    confirm_new_password: "Confirm new password",
    passwords_dont_match: "Passwords do not match",
    password_changed: "Password changed successfully!",
    admin_your_name: "Your name (administrator)",
    terms_of_service: "Terms of Service",
    privacy_policy: "Privacy Policy",
    fill_password_fields: "Please fill in all password fields",
    error_change_password: "Error changing password",
    fill_email_password: "Please enter your email and password",
    invalid_credentials: "Incorrect email or password. Please try again.",
    welcome_back: "Welcome back!",
    or: "or",
    fill_required_fields: "Please fill in name, email, password and restaurant code",
    fill_all_required: "Please fill in all required fields",
    password_min_length: "Password must be at least 6 characters",
    error_register: "Registration error",
    error_create_restaurant: "Error creating restaurant",
    fill_form_below: "Fill in the details below",
    error_pdf: "Error generating PDF report.",
    notifications: "Notifications",
    no_notifications: "No notifications",
    notifications_appear_here: "Order updates will appear here",
  },
  "pt-PT": {
    app_name: "OrderControl",
    home: "Início",
    menu: "Menu",
    cart: "Carrinho",
    orders: "Encomendas",
    profile: "Perfil",
    admin: "Admin",
    dashboard: "Painel",
    settings: "Definições",
    save: "Guardar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Adicionar",
    search: "Pesquisar",
    loading: "A carregar...",
    error: "Erro",
    success: "Sucesso",
    back: "Voltar",
    logout: "Sair",
    login: "Entrar",
    register: "Registar",
    email: "E-mail",
    password: "Palavra-passe",
    name: "Nome completo",
    phone: "Telefone",
    address: "Morada",
    city: "Cidade",
    zip_code: "Código Postal",
    admin_login: "Acesso Administrativo",
    customer_login: "Acesso do Cliente",
    dont_have_account: "Não tem conta?",
    already_have_account: "Já tem conta?",
    forgot_password: "Esqueceu a palavra-passe?",
    welcome: "Bem-vindo,",
    featured: "Destaques",
    categories: "Categorias",
    see_menu: "Ver Menu",
    contact_whatsapp: "Falar no WhatsApp",
    open_now: "Aberto agora",
    closed: "Fechado",
    opening_hours: "Horário de funcionamento",
    add_to_cart: "Adicionar ao carrinho",
    description: "Descrição",
    price: "Preço",
    extras: "Extras",
    quantity: "Quantidade",
    empty_cart: "Carrinho vazio",
    empty_cart_desc: "Adicione itens do menu para começar a sua encomenda",
    subtotal: "Subtotal",
    delivery_fee: "Taxa de entrega",
    total: "Total",
    checkout: "Finalizar Encomenda",
    remove: "Remover",
    delivery: "Entrega",
    pickup: "Levantar",
    payment_method: "Método de pagamento",
    pix: "PIX",
    cash: "Numerário",
    credit_card: "Cartão de Crédito",
    pay_on_delivery: "Pagar na Entrega",
    neighborhood: "Bairro",
    reference: "Ponto de referência",
    place_order: "Fazer Encomenda",
    order_confirmed: "Encomenda confirmada!",
    order_number: "Número da encomenda",
    estimated_time: "Tempo estimado",
    minutes: "minutos",
    order_received: "Encomenda recebida",
    preparing: "A preparar",
    ready: "Pronta",
    out_for_delivery: "Em entrega",
    delivered: "Entregue",
    cancelled: "Cancelada",
    track_order: "Seguir encomenda",
    order_history: "Histórico de encomendas",
    orders_today: "Encomendas hoje",
    revenue_today: "Receita hoje",
    active_orders: "Encomendas ativas",
    monthly_revenue: "Receita mensal",
    most_sold: "Mais vendidos",
    new_order: "Nova encomenda",
    accept: "Aceitar",
    reject: "Rejeitar",
    product_name: "Nome do produto",
    category: "Categoria",
    image: "Imagem",
    available: "Disponível",
    unavailable: "Indisponível",
    add_product: "Adicionar produto",
    edit_product: "Editar produto",
    promotions: "Promoções",
    discount: "Desconto",
    original_price: "Preço original",
    promo_price: "Preço promocional",
    active: "Ativo",
    inactive: "Inativo",
    restaurant_name: "Nome do restaurante",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Redes Sociais",
    delivery_areas: "Zonas de Entrega",
    min_order: "Encomenda mínima",
    daily_report: "Relatório Diário",
    monthly_report: "Relatório Mensal",
    export_pdf: "Exportar PDF",
    my_orders: "As Minhas Encomendas",
    saved_addresses: "Moradas guardadas",
    edit_profile: "Editar perfil",
    language: "Idioma",
    chat: "Chat",
    chat_support: "Chat com Suporte",
    customer_chats: "Conversas dos Clientes",
    messages: "Mensagens",
    send: "Enviar",
    write_message: "Escreva uma mensagem...",
    no_messages: "Nenhuma mensagem ainda",
    start_conversation: "Inicie uma conversa com o restaurante!",
    login_to_chat: "Inicie sessão para aceder ao suporte",
    restaurant_online: "Online • Responde rapidamente",
    restaurant_info: "Informações do Restaurante",
    cover_photo: "Foto de Capa",
    logo_photo: "Logo do Restaurante",
    logo_photo_desc: "Toque para alterar o logo",
    change_photo: "Alterar foto",
    save_changes: "Guardar Alterações",
    saving: "A guardar...",
    changes_saved: "Definições guardadas com sucesso!",
    tagline: "Slogan do restaurante",
    phone_label: "Telefone",
    social_links: "Redes Sociais",
    manage_orders: "Gerir Encomendas",
    management: "Gestão",
    active_orders_section: "Encomendas Ativas",
    see_all: "Ver todos",
    ready_btn: "Pronta",
    send_btn: "Enviar",
    delivered_btn: "Entregue",
    admin_panel: "Painel Admin",
    hello: "Olá,",
    view_store: "Ver Loja",
    login_to_manage: "Inicie sessão para gerir o seu perfil",
    register_link: "Registar",
    admin_badge: "ADMINISTRADOR",
    access_admin: "Aceder ao Painel Admin",
    no_orders_yet: "Nenhuma encomenda ainda",
    no_orders_desc: "As suas encomendas aparecerão aqui",
    order_items: "Itens da Encomenda",
    order_summary: "Resumo da Encomenda",
    delivery_type: "Tipo de Entrega",
    delivery_address_section: "Morada de Entrega",
    prefer_whatsapp: "Prefere encomendar pelo WhatsApp?",
    order_via_whatsapp: "Encomendar pelo WhatsApp",
    processing: "A processar...",
    confirm_order: "Confirmar Encomenda",
    info: "Informação",
    free: "Grátis",
    pix: "PIX",
    login_to_view_orders: "Inicie sessão para ver as suas encomendas",
    make_first_order: "Faça a sua primeira encomenda!",
    order_not_found: "Encomenda não encontrada",
    product_not_found: "Produto não encontrado",
    order_problem: "Problemas com a sua encomenda?",
    login_required: "Inicie sessão para continuar",
    provide_delivery_address: "Informe o endereço de entrega",
    summary: "Resumo",
    item_singular: "artigo",
    items_plural: "artigos",
    status_received: "Encomenda recebida",
    status_preparing: "A preparar",
    status_ready: "Pronta para entrega",
    status_delivering: "Em entrega",
    status_delivered: "Entregue",
    status_cancelled: "Cancelada",
    whatsapp_default_msg: "Olá! Gostaria de fazer uma encomenda.",
    whatsapp_order_inquiry: "Olá! Tenho uma dúvida sobre a encomenda",
    total_orders: "Total de encomendas",
    total_revenue: "Receita total",
    avg_order: "Valor médio",
    today: "Hoje",
    week: "Semana",
    month_label: "Mês",
    best_sellers: "Produtos mais vendidos",
    recent_orders_section: "Encomendas recentes",
    no_data: "Nenhum dado disponível",
    no_orders_period: "Sem encomendas neste período",
    savings: "Poupança",
    advance_to: "Avançar para:",
    no_orders_found: "Nenhuma encomenda encontrada",
    reports_title: "Relatórios",
    all_filter: "Todos",
    received_plural: "Recebidas",
    ready_plural: "Prontas",
    delivered_plural: "Entregues",
    cancelled_plural: "Canceladas",
    delivering_filter: "Entrega",
    remove: "Remover",
    export_btn: "Exportar",
    products: "Produtos",
    n_products: "{n} produtos",
    register_customer: "Criar conta de cliente",
    register_customer_title: "Criar conta de cliente",
    create_restaurant: "Criar Restaurante",
    create_restaurant_subtitle: "Registe o seu restaurante e comece a receber encomendas",
    create_restaurant_btn: "Criar o meu restaurante",
    enter_restaurant_code: "Código do restaurante",
    restaurant_code_hint: "Peça o código de 6 dígitos ao proprietário do restaurante",
    your_restaurant_code: "Código do seu restaurante",
    share_code_hint: "Partilhe este código com os seus clientes para que se registem na app",
    copy: "Copiar",
    copied: "Copiado!",
    restaurant_created: "Restaurante criado com sucesso!",
    code_save_hint: "Guarde este código. Também está disponível em Admin → Definições.",
    change_password: "Alterar Senha",
    current_password: "Senha actual",
    new_password: "Nova senha",
    confirm_password: "Confirmar senha",
    confirm_new_password: "Confirmar nova senha",
    passwords_dont_match: "As senhas não coincidem",
    password_changed: "Senha alterada com sucesso!",
    admin_your_name: "O seu nome (administrador)",
  },
  "es": {
    app_name: "OrderControl",
    home: "Inicio",
    menu: "Menú",
    cart: "Carrito",
    orders: "Pedidos",
    profile: "Perfil",
    admin: "Admin",
    dashboard: "Panel",
    settings: "Configuración",
    save: "Guardar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Agregar",
    search: "Buscar",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    back: "Volver",
    logout: "Salir",
    login: "Entrar",
    register: "Registrarse",
    email: "Correo",
    password: "Contraseña",
    name: "Nombre completo",
    phone: "Teléfono",
    address: "Dirección",
    city: "Ciudad",
    zip_code: "Código postal",
    admin_login: "Acceso Admin",
    customer_login: "Acceso Cliente",
    dont_have_account: "¿No tienes cuenta?",
    already_have_account: "¿Ya tienes cuenta?",
    forgot_password: "¿Olvidaste tu contraseña?",
    welcome: "¡Bienvenido,",
    featured: "Destacados",
    categories: "Categorías",
    see_menu: "Ver Menú",
    contact_whatsapp: "Contactar por WhatsApp",
    open_now: "Abierto ahora",
    closed: "Cerrado",
    opening_hours: "Horario de atención",
    add_to_cart: "Agregar al carrito",
    description: "Descripción",
    price: "Precio",
    extras: "Extras",
    quantity: "Cantidad",
    empty_cart: "Carrito vacío",
    empty_cart_desc: "Agrega artículos del menú para comenzar tu pedido",
    subtotal: "Subtotal",
    delivery_fee: "Costo de entrega",
    total: "Total",
    checkout: "Finalizar Pedido",
    remove: "Eliminar",
    delivery: "Entrega",
    pickup: "Recoger",
    payment_method: "Método de pago",
    pix: "PIX",
    cash: "Efectivo",
    credit_card: "Tarjeta de crédito",
    pay_on_delivery: "Pagar al recibir",
    neighborhood: "Barrio",
    reference: "Punto de referencia",
    place_order: "Hacer Pedido",
    order_confirmed: "¡Pedido confirmado!",
    order_number: "Número de pedido",
    estimated_time: "Tiempo estimado",
    minutes: "minutos",
    order_received: "Pedido recibido",
    preparing: "Preparando",
    ready: "Listo",
    out_for_delivery: "En camino",
    delivered: "Entregado",
    cancelled: "Cancelado",
    track_order: "Seguir pedido",
    order_history: "Historial de pedidos",
    orders_today: "Pedidos hoy",
    revenue_today: "Ingresos hoy",
    active_orders: "Pedidos activos",
    monthly_revenue: "Ingresos mensuales",
    most_sold: "Más vendidos",
    new_order: "Nuevo pedido",
    accept: "Aceptar",
    reject: "Rechazar",
    product_name: "Nombre del producto",
    category: "Categoría",
    image: "Imagen",
    available: "Disponible",
    unavailable: "No disponible",
    add_product: "Agregar producto",
    edit_product: "Editar producto",
    promotions: "Promociones",
    discount: "Descuento",
    original_price: "Precio original",
    promo_price: "Precio promocional",
    active: "Activo",
    inactive: "Inactivo",
    restaurant_name: "Nombre del restaurante",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Redes Sociales",
    delivery_areas: "Áreas de entrega",
    min_order: "Pedido mínimo",
    daily_report: "Informe diario",
    monthly_report: "Informe mensual",
    export_pdf: "Exportar PDF",
    my_orders: "Mis Pedidos",
    saved_addresses: "Direcciones guardadas",
    edit_profile: "Editar perfil",
    language: "Idioma",
    chat: "Chat",
    chat_support: "Chat de Soporte",
    customer_chats: "Conversaciones de Clientes",
    messages: "Mensajes",
    send: "Enviar",
    write_message: "Escribe un mensaje...",
    no_messages: "Sin mensajes aún",
    start_conversation: "¡Inicia una conversación con el restaurante!",
    login_to_chat: "Inicia sesión para acceder al soporte",
    restaurant_online: "En línea • Responde rápidamente",
    restaurant_info: "Información del Restaurante",
    cover_photo: "Foto de Portada",
    logo_photo: "Logo del Restaurante",
    logo_photo_desc: "Toca para cambiar el logo",
    change_photo: "Cambiar foto",
    save_changes: "Guardar Cambios",
    saving: "Guardando...",
    changes_saved: "¡Configuración guardada con éxito!",
    tagline: "Eslogan del restaurante",
    phone_label: "Teléfono",
    social_links: "Redes Sociales",
    manage_orders: "Gestionar Pedidos",
    management: "Gestión",
    active_orders_section: "Pedidos Activos",
    see_all: "Ver todos",
    ready_btn: "Listo",
    send_btn: "Enviar",
    delivered_btn: "Entregado",
    admin_panel: "Panel Admin",
    hello: "¡Hola,",
    view_store: "Ver Tienda",
    login_to_manage: "Inicia sesión para gestionar tu perfil",
    register_link: "Regístrate",
    admin_badge: "ADMINISTRADOR",
    access_admin: "Acceder al Panel Admin",
    no_orders_yet: "Sin pedidos aún",
    no_orders_desc: "Tus pedidos aparecerán aquí",
    order_items: "Artículos del Pedido",
    order_summary: "Resumen del Pedido",
    delivery_type: "Tipo de Entrega",
    delivery_address_section: "Dirección de Entrega",
    prefer_whatsapp: "¿Prefieres pedir por WhatsApp?",
    order_via_whatsapp: "Pedir por WhatsApp",
    processing: "Procesando...",
    confirm_order: "Confirmar Pedido",
    info: "Información",
    free: "Gratis",
    pix: "PIX",
    login_to_view_orders: "Inicia sesión para ver tus pedidos",
    no_orders_yet: "Ningún pedido aún",
    make_first_order: "¡Haz tu primer pedido!",
    order_not_found: "Pedido no encontrado",
    product_not_found: "Producto no encontrado",
    order_problem: "¿Problemas con tu pedido?",
    login_required: "Inicia sesión para continuar",
    provide_delivery_address: "Ingresa tu dirección de entrega",
    summary: "Resumen",
    item_singular: "artículo",
    items_plural: "artículos",
    status_received: "Pedido recibido",
    status_preparing: "Preparando",
    status_ready: "Listo para entregar",
    status_delivering: "En camino",
    status_delivered: "Entregado",
    status_cancelled: "Cancelado",
    whatsapp_default_msg: "¡Hola! Me gustaría hacer un pedido.",
    whatsapp_order_inquiry: "¡Hola! Tengo una consulta sobre el pedido",
    total_orders: "Total de pedidos",
    total_revenue: "Ingresos totales",
    avg_order: "Pedido promedio",
    today: "Hoy",
    week: "Semana",
    month_label: "Mes",
    best_sellers: "Más vendidos",
    recent_orders_section: "Pedidos recientes",
    no_data: "Sin datos disponibles",
    no_orders_period: "Sin pedidos en este período",
    savings: "Ahorro",
    advance_to: "Avanzar a:",
    no_orders_found: "Ningún pedido encontrado",
    reports_title: "Informes",
    all_filter: "Todos",
    received_plural: "Recibidos",
    ready_plural: "Listos",
    delivered_plural: "Entregados",
    cancelled_plural: "Cancelados",
    delivering_filter: "Entrega",
    remove: "Eliminar",
    export_btn: "Exportar",
    products: "Productos",
    n_products: "{n} productos",
    register_customer: "Registrarse como cliente",
    register_customer_title: "Crear cuenta de cliente",
    create_restaurant: "Crear Restaurante",
    create_restaurant_subtitle: "Registra tu restaurante y empieza a recibir pedidos",
    create_restaurant_btn: "Crear mi restaurante",
    enter_restaurant_code: "Código del restaurante",
    restaurant_code_hint: "Pide el código de 6 dígitos al dueño del restaurante",
    your_restaurant_code: "Código de tu restaurante",
    share_code_hint: "Comparte este código con tus clientes para que se registren en la app",
    copy: "Copiar",
    copied: "¡Copiado!",
    restaurant_created: "¡Restaurante creado con éxito!",
    code_save_hint: "Guarda este código. También está disponible en Admin → Configuración.",
    change_password: "Cambiar Contraseña",
    current_password: "Contraseña actual",
    new_password: "Nueva contraseña",
    confirm_password: "Confirmar contraseña",
    confirm_new_password: "Confirmar nueva contraseña",
    passwords_dont_match: "Las contraseñas no coinciden",
    password_changed: "¡Contraseña cambiada con éxito!",
    admin_your_name: "Tu nombre (administrador)",
  },
  "fr": {
    app_name: "OrderControl",
    home: "Accueil",
    menu: "Menu",
    cart: "Panier",
    orders: "Commandes",
    profile: "Profil",
    admin: "Admin",
    dashboard: "Tableau de bord",
    settings: "Paramètres",
    save: "Enregistrer",
    cancel: "Annuler",
    confirm: "Confirmer",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    search: "Rechercher",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    back: "Retour",
    logout: "Déconnexion",
    login: "Connexion",
    register: "S'inscrire",
    email: "Email",
    password: "Mot de passe",
    name: "Nom complet",
    phone: "Téléphone",
    address: "Adresse",
    city: "Ville",
    zip_code: "Code postal",
    admin_login: "Accès Admin",
    customer_login: "Accès Client",
    dont_have_account: "Pas de compte?",
    already_have_account: "Déjà un compte?",
    forgot_password: "Mot de passe oublié?",
    welcome: "Bienvenue,",
    featured: "À la une",
    categories: "Catégories",
    see_menu: "Voir le Menu",
    contact_whatsapp: "Contacter via WhatsApp",
    open_now: "Ouvert maintenant",
    closed: "Fermé",
    opening_hours: "Heures d'ouverture",
    add_to_cart: "Ajouter au panier",
    description: "Description",
    price: "Prix",
    extras: "Suppléments",
    quantity: "Quantité",
    empty_cart: "Panier vide",
    empty_cart_desc: "Ajoutez des articles du menu pour commencer votre commande",
    subtotal: "Sous-total",
    delivery_fee: "Frais de livraison",
    total: "Total",
    checkout: "Finaliser la Commande",
    remove: "Supprimer",
    delivery: "Livraison",
    pickup: "À emporter",
    payment_method: "Mode de paiement",
    pix: "PIX",
    cash: "Espèces",
    credit_card: "Carte de crédit",
    pay_on_delivery: "Payer à la livraison",
    neighborhood: "Quartier",
    reference: "Point de référence",
    place_order: "Passer la Commande",
    order_confirmed: "Commande confirmée!",
    order_number: "Numéro de commande",
    estimated_time: "Délai estimé",
    minutes: "minutes",
    order_received: "Commande reçue",
    preparing: "En préparation",
    ready: "Prête",
    out_for_delivery: "En livraison",
    delivered: "Livrée",
    cancelled: "Annulée",
    track_order: "Suivre la commande",
    order_history: "Historique des commandes",
    orders_today: "Commandes aujourd'hui",
    revenue_today: "Revenus aujourd'hui",
    active_orders: "Commandes actives",
    monthly_revenue: "Revenus mensuels",
    most_sold: "Les plus vendus",
    new_order: "Nouvelle commande",
    accept: "Accepter",
    reject: "Refuser",
    product_name: "Nom du produit",
    category: "Catégorie",
    image: "Image",
    available: "Disponible",
    unavailable: "Indisponible",
    add_product: "Ajouter un produit",
    edit_product: "Modifier le produit",
    promotions: "Promotions",
    discount: "Réduction",
    original_price: "Prix original",
    promo_price: "Prix promotionnel",
    active: "Actif",
    inactive: "Inactif",
    restaurant_name: "Nom du restaurant",
    whatsapp: "WhatsApp",
    logo: "Logo",
    social_media: "Réseaux Sociaux",
    delivery_areas: "Zones de livraison",
    min_order: "Commande minimum",
    daily_report: "Rapport journalier",
    monthly_report: "Rapport mensuel",
    export_pdf: "Exporter PDF",
    my_orders: "Mes Commandes",
    saved_addresses: "Adresses enregistrées",
    edit_profile: "Modifier le profil",
    language: "Langue",
    chat: "Chat",
    chat_support: "Chat Support",
    customer_chats: "Conversations Clients",
    messages: "Messages",
    send: "Envoyer",
    write_message: "Écrire un message...",
    no_messages: "Aucun message pour l'instant",
    start_conversation: "Commencez une conversation avec le restaurant!",
    login_to_chat: "Connectez-vous pour accéder au support",
    restaurant_online: "En ligne • Répond rapidement",
    restaurant_info: "Informations du Restaurant",
    cover_photo: "Photo de Couverture",
    logo_photo: "Logo du Restaurant",
    logo_photo_desc: "Touchez pour changer le logo",
    change_photo: "Changer la photo",
    save_changes: "Enregistrer les Modifications",
    saving: "Enregistrement...",
    changes_saved: "Paramètres enregistrés avec succès!",
    tagline: "Slogan du restaurant",
    phone_label: "Téléphone",
    social_links: "Réseaux Sociaux",
    manage_orders: "Gérer les Commandes",
    management: "Gestion",
    active_orders_section: "Commandes Actives",
    see_all: "Voir tout",
    ready_btn: "Prête",
    send_btn: "Envoyer",
    delivered_btn: "Livrée",
    admin_panel: "Panneau Admin",
    hello: "Bonjour,",
    view_store: "Voir la Boutique",
    login_to_manage: "Connectez-vous pour gérer votre profil",
    register_link: "S'inscrire",
    admin_badge: "ADMINISTRATEUR",
    access_admin: "Accéder au Panneau Admin",
    no_orders_yet: "Aucune commande pour l'instant",
    no_orders_desc: "Vos commandes apparaîtront ici",
    order_items: "Articles de la Commande",
    order_summary: "Récapitulatif de la Commande",
    delivery_type: "Type de Livraison",
    delivery_address_section: "Adresse de Livraison",
    prefer_whatsapp: "Préférez-vous commander via WhatsApp?",
    order_via_whatsapp: "Commander via WhatsApp",
    processing: "Traitement...",
    confirm_order: "Confirmer la Commande",
    info: "Information",
    free: "Gratuit",
    pix: "PIX",
    login_to_view_orders: "Connectez-vous pour voir vos commandes",
    no_orders_yet: "Aucune commande pour l'instant",
    make_first_order: "Passez votre première commande!",
    order_not_found: "Commande introuvable",
    product_not_found: "Produit introuvable",
    order_problem: "Un problème avec votre commande?",
    login_required: "Connectez-vous pour continuer",
    provide_delivery_address: "Veuillez entrer votre adresse de livraison",
    summary: "Résumé",
    item_singular: "article",
    items_plural: "articles",
    status_received: "Commande reçue",
    status_preparing: "En préparation",
    status_ready: "Prête à livrer",
    status_delivering: "En livraison",
    status_delivered: "Livrée",
    status_cancelled: "Annulée",
    whatsapp_default_msg: "Bonjour! Je voudrais passer une commande.",
    whatsapp_order_inquiry: "Bonjour! J'ai une question sur la commande",
    total_orders: "Total des commandes",
    total_revenue: "Chiffre d'affaires",
    avg_order: "Commande moyenne",
    today: "Aujourd'hui",
    week: "Semaine",
    month_label: "Mois",
    best_sellers: "Meilleures ventes",
    recent_orders_section: "Commandes récentes",
    no_data: "Aucune donnée disponible",
    no_orders_period: "Aucune commande sur cette période",
    savings: "Économies",
    advance_to: "Passer à:",
    no_orders_found: "Aucune commande trouvée",
    reports_title: "Rapports",
    all_filter: "Tous",
    received_plural: "Reçues",
    ready_plural: "Prêtes",
    delivered_plural: "Livrées",
    cancelled_plural: "Annulées",
    delivering_filter: "Livraison",
    remove: "Supprimer",
    export_btn: "Exporter",
    products: "Produits",
    n_products: "{n} produits",
    register_customer: "S'inscrire comme client",
    register_customer_title: "Créer un compte client",
    create_restaurant: "Créer un Restaurant",
    create_restaurant_subtitle: "Enregistrez votre restaurant et commencez à recevoir des commandes",
    create_restaurant_btn: "Créer mon restaurant",
    enter_restaurant_code: "Code du restaurant",
    restaurant_code_hint: "Demandez le code à 6 chiffres au propriétaire du restaurant",
    your_restaurant_code: "Code de votre restaurant",
    share_code_hint: "Partagez ce code avec vos clients pour qu'ils s'inscrivent sur l'application",
    copy: "Copier",
    copied: "Copié!",
    restaurant_created: "Restaurant créé avec succès!",
    code_save_hint: "Sauvegardez ce code. Il est aussi disponible dans Admin → Paramètres.",
    change_password: "Changer le Mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    confirm_password: "Confirmer le mot de passe",
    confirm_new_password: "Confirmer le nouveau mot de passe",
    passwords_dont_match: "Les mots de passe ne correspondent pas",
    password_changed: "Mot de passe changé avec succès!",
    admin_your_name: "Votre nom (administrateur)",
  },
};

const LangContext = createContext<{
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
  formatCurrency: (amount: number) => string;
} | null>(null);

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("pt-BR");

  useEffect(() => {
    AsyncStorage.getItem("@ordercontrol_lang").then((l) => {
      if (l) setLanguageState(l as Language);
    });
  }, []);

  function setLanguage(l: Language) {
    setLanguageState(l);
    AsyncStorage.setItem("@ordercontrol_lang", l);
  }

  function t(key: string): string {
    return translations[language][key] ?? translations["pt-BR"][key] ?? key;
  }

  function formatCurrency(amount: number): string {
    const fixed = amount.toFixed(2);
    const commaFixed = fixed.replace(".", ",");
    switch (language) {
      case "pt-BR":
        return `R$ ${commaFixed}`;
      case "pt-PT":
        return `${commaFixed} €`;
      case "en":
        return `$${fixed}`;
      case "es":
        return `$${commaFixed}`;
      case "fr":
        return `${commaFixed} €`;
      default:
        return `R$ ${commaFixed}`;
    }
  }

  return (
    <LangContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
